
version: '3'
services:
  ui:
    image: ${DOCKER_REPO}/registry-ui:${COMMIT_ID:-test}-${BUILD_ENV:-dev}

    build:
      context: .
      dockerfile: "docker-builds/ui/Dockerfile"
      args:
          BUILD_ENV: "${BUILD_ENV:-dev}"
    networks:
      - dev_network
    environment:
      - PORT=80

  server:
    image: ${DOCKER_REPO}/registry-server:${COMMIT_ID:-test}-${BUILD_ENV:-dev}
    build:
      context: .
      dockerfile: "docker-builds/server/Dockerfile"
      args:
          BUILD_ENV: "${BUILD_ENV:-dev}"
    volumes:
      - /home/$USER/logs:/logs
      - /home/$USER/configs:/configs
    networks:
      - dev_network
    environment:
      - PORT=6200

networks:
  dev_network:

volumes:
  vol_node_modules:
  vol_m2_cache:
  vol_ipfs_data:
  vol_server_tests:
  vol_target:
