version: "3"
services:
  ui:
    image: ${DOCKER_REPO}/registry-ui:${COMMIT_ID:-test}-${BUILD_ENV:-dev}

    build:
      context: .
      dockerfile: "docker-builds/ui/Dockerfile"
      args:
        BUILD_ENV: "${BUILD_ENV:-dev}"
    networks:
      - dev_network
    environment:
      - PORT=80

  server:
    image: ${DOCKER_REPO}/registry-server:${COMMIT_ID:-test}-${BUILD_ENV:-dev}
    build:
      context: .
      dockerfile: "docker-builds/server/Dockerfile"
      args:
        BUILD_ENV: "${BUILD_ENV:-dev}"
    volumes:
      - /home/$USER/logs:/logs
      - /home/$USER/configs:/configs
    networks:
      - dev_network
    environment:
      - PORT=6200

  ganache:
    image: 0xorg/ganache-cli:latest
    networks:
      - dev_network
    ports:
      - 8545:8545
      - 8549:8549
    environment:
      VERSION: 8.0.1
      CHAIN_ID: 1337
      NETWORK_ID: 1337

  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
      - vol_ipfs_data:/data/ipfs
    networks:
      - dev_network
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 5001:5001
      - 8080:8080

networks:
  dev_network:

volumes:
  vol_node_modules:
  vol_m2_cache:
  vol_ipfs_data:
  vol_server_tests:
  vol_target:
