(ns district-registry.ui.terms.page
  (:require
    [district-registry.ui.components.app-layout :refer [app-layout]]
    [district-registry.ui.components.nav :as nav]
    [district.ui.component.page :refer [page]]
    [re-frame.core :refer [subscribe]]))

(defmethod page :route/terms []
  (fn []
    [app-layout
     [:section#main
      [:div.container
       [:div.box-wrap
        [:div.hero
         [:div.container
          [:div.page-title [:h1 "Terms Of Use"]]]]
        [:div.body-text
         [:div.container
          [:h3 "1. ACCEPTANCE OF TERMS"]
          [:p "The services that district0x provides to You through its website district0x.io, mobile application(s), and related services (collectively, the “District Registry”) are subject to the following Terms of Use (“TOU”). BY ACCESSING THE DISTRICT REGISTRY, YOU AGREE TO BOTH THE district0x.IO (“district0x”) TERMS OF USE AND THE district0x " [nav/a {:route [:route/privacy-policy]} "PRIVACY POLICY"]]
          [:p "district0x reserves the right to update the TOU at any time without notice to You. The most current version of the TOU can be reviewed by clicking on the “Terms of Use” hypertext link located at the bottom of our Web pages located at district0x.io."]
          [:p "district0x shall have the right at any time to change or discontinue any aspect or feature of the District Registry, including, but not limited to, content, access, or use."]
          [:h3 "2. DESCRIPTION OF THE DISTRICT REGISTRY"]
          [:p "The District Registry is a decentrally-maintained smart contract (a token curated registry) that makes use of a deposit and challenge effort to allow token holders to maintain a whitelist of approved members in a decentralized manner, and that stores the credentials of districts that have been granted access to the district0x Network. The presence of a district in the District Registry signifies that the district has been accredited by DNT holders as non-malicious and an appropriate addition to the district0x Network via an incentivized voting game."]
          [:p "When a prospective district wishes to apply for access to be included on the District Registry, they will submit a DNT deposit with their application to the registry, initiating a challenge period during which any DNT holder can challenge submissions that they believe are not appropriate for the district0x Network or that could put the network at risk. Token holders can challenge the application by depositing an equal amount of DNT to the registry, opening a voting period during which all DNT holders can vote for inclusion or denial of the specified district in the registry."]
          [:p "DNT holders are incentivized to participate in the challenge and voting process to ensure that districts added to the network are acceptable to the community. Participants on the winning side of a vote also stand to receive a portion of the deposit made by the losing party in the event."]
          [:h3 "3. USE OF THE DISTRICT REGISTRY"]
          [:p "You agree to use the District Registry for lawful purposes only, and solely in a manner consistent with the intent of district0x pursuant to the Description of the District Registry, above. You agree that You will not: use the District Registry in connection with surveys, contests, pyramid schemes, chain letters, junk email, spamming, or any duplicative or unsolicited messages (commercial or otherwise), defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others, publish, post, distribute or disseminate any inappropriate, profane, defamatory, obscene, indecent or unlawful topic, name, material, or information."]
          [:p "You agree you will not upload, or otherwise make available, files that contain images, photographs, software or other material protected by intellectual property laws, including, by way of example, and not as limitation, copyright or trademark laws (or by rights of privacy or publicity) unless You own or control the rights thereto or have received all necessary consent to do the same, use any material or information, including images or photographs, which are made available by or through the District Registry in any manner that infringes any copyright, trademark, patent, trade secret, or other proprietary right of any party, upload files that contain viruses, Trojan horses, worms, time bombs, cancelbots, corrupted files, or any other similar software or programs that may damage the operation of another’s computer or damage the property of another, advertise or offer to sell or buy any goods or services for any business purpose, falsify or delete any copyright management information such as author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded, violate any code of conduct or other guidelines that may be applicable to the District Registry, harvest or otherwise collect information about others, including email addresses, violate any applicable laws or regulations, create a false identity for the purpose of misleading others.  You understand that any violation of these Terms of Use, including providing false or misleading information, can lead to your removal from the District Registry or use of the District Registry, and district0x maintains sole discretion over whether to remove You for such violation."]
          [:p "You shall be solely liable for any damage resulting from any infringement of copyrights, proprietary rights, or any other harm resulting from such a submission. The foregoing provisions of this Section 3 are for the benefit of district0x, its subsidiaries, affiliates and its third-party content providers and licensors, and each shall have the right to assert and enforce such provisions directly or on its own behalf."]
          [:p "district0x reserves the right to terminate Your access to the District Registry at any time, without notice, for any reason whatsoever. district0x reserves the right at all times to disclose any information it deems necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in its sole discretion. Materials uploaded to the District Registry may be subject to posted limitations on usage, reproduction and/or dissemination; You are responsible for adhering to such limitations if You download the materials. Always use caution when giving out any personally identifiable information in the District Registry. district0x does not control or endorse the third-party content, messages, or information found in any of the District Registry.  district0x disclaims any liability with regard to the District Registry, and any actions resulting from Your participation in District Registry. Managers and hosts are not authorized district0x spokespersons, and their views do not necessarily reflect those of district0x."]
          [:h3 "4. MEMBER ACCOUNT, PASSWORD, AND SECURITY"]
          [:p "You agree that you are human, and that you will complete the registration process by providing district0x with current, complete and accurate information as prompted by the applicable registration form. You will also choose a password and a username. You are entirely responsible for maintaining the confidentiality and security of Your password and account. Furthermore, You are entirely responsible for any and all content posted and activities that occur under Your account. You agree to notify district0x immediately of any unauthorized use of Your account or any other breach of security. YOU WILL NOT HOLD district0x LIABLE FOR ANY LOSS THAT YOU MAY INCUR AS A RESULT OF ANY MISUSE OF YOUR LOGIN INFORMATION, WHETHER WITH OR WITHOUT YOUR KNOWLEDGE.  You acknowledge that you may be held liable for losses incurred by district0x or another party due to someone else using Your account or password. You may not use anyone else’s account at any time, without the permission of the account holder.  Any account created by a “bot” or other automated methods will be banned from the District Registry."]
          [:p "By agreeing to these Terms, You warrant that You are at least 18 years old. If you are under 18 years old, You may not take part in or use the District Registry."]
          [:h3 "5. DISCLAIMER"]
          [:p "YOU EXPRESSLY AGREE THAT USE OF THE DISTRICT REGISTRY IS AT YOUR SOLE RISK. NEITHER district0x, ITS AFFILIATES, NOR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, OWNERS, EMPLOYEES, AGENTS, THIRD-PARTY CONTENT PROVIDERS OR LICENSORS, WILL BE LIABLE FOR ANY USE OR MISUSE OF THE DISTRICT REGISTRY, OR FOR ANY DECISION MADE THROUGH THE DECENTRALIZED PROCESS IN WHICH NETWORK PARTICIPANTS TAKE PART.  NEITHER district0x, ITS AFFILIATES, NOR ANY OF THEIR RESPECTIVE EMPLOYEES, AGENTS, THIRD-PARTY CONTENT PROVIDERS OR LICENSORS, WARRANT THAT THE DISTRICT REGISTRY WILL BE UNINTERRUPTED OR ERROR FREE; NOR DO THEY MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE DISTRICT REGISTRY, OR AS TO THE ACCURACY, RELIABILITY OR CONTENT OF ANY INFORMATION, SERVICE, MATERIALS, OR MERCHANDISE PROVIDED THROUGH THE DISTRICT REGISTRY. THE DISTRICT REGISTRY IS PROVIDED ON AN “AS IS” BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF TITLE, IMPLIED WARRANTIES OF MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE, OTHER THAN THOSE WARRANTIES THAT ARE IMPLIED BY AND INCAPABLE OF EXCLUSION, RESTRICTION OR MODIFICATION, UNDER THE LAWS APPLICABLE TO THESE TERMS OF USE."]
          [:p "WITHOUT LIMITING THE FOREGOING, THIS DISCLAIMER OF LIABILITY APPLIES TO ANY DAMAGES OR INJURY CAUSED BY ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, WHETHER BY COMPUTER VIRUS, COMMUNICATION LINE FAILURE, THEFT OR DESTRUCTION, OR UNAUTHORIZED ACCESS TO, ALTERATION OF, OR OTHER USE OF, THE DISTRICT REGISTRY AND ANY MATERIALS OR CONTENT FOUND THEREIN, WHETHER UNDER A CLAIM FOR BREACH OF CONTRACT, TORTIOUS BEHAVIOR, NEGLIGENCE, OR UNDER ANY OTHER CAUSE OF ACTION."]
          [:p "YOU ACKNOWLEDGE THAT district0x IS NOT LIABLE FOR THE DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF OTHER USERS, AND THAT YOU ALONE ARE ASSUMING THE RISK OF INJURY FROM THE FOREGOING, TO THE FULLEST EXTENT OF THE LAW. IN NO EVENT WILL district0x, ITS AFFILIATES, ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, OWNERS, EMPLOYEES, AGENTS, THIRD-PARTY CONTENT PROVIDERS, LICENSORS OR ANY OTHER PERSON OR ENTITY INVOLVED IN CREATING, PRODUCING, OR PROVIDING THE DISTRICT REGISTRY, BE LIABLE FOR ANY DAMAGES, INCLUDING, WITHOUT LIMITATION, DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES ARISING OUT OF THE USE OF OR INABILITY TO USE THE DISTRICT REGISTRY. IN ADDITION TO THE TERMS SET FORTH ABOVE, NEITHER district0x NOR ITS AFFILIATES, INFORMATION PROVIDERS, OR CONTENT PARTNERS, SHALL BE LIABLE REGARDLESS OF THE CAUSE OR DURATION, FOR ANY ERRORS, INACCURACIES, OMISSIONS, OR OTHER DEFECTS IN, OR UNTIMELINESS OR UNAUTHENTICITY OF, THE INFORMATION CONTAINED WITHIN THE DISTRICT REGISTRY, OR FOR ANY DELAY OR INTERRUPTION IN THE TRANSMISSION OR PROVISION THEREOF TO YOU, OR FOR ANY CLAIMS OR LOSSES ARISING THEREFROM OR OCCASIONED THEREBY. district0x SHALL NOT BE LIABLE FOR ANY THIRD-PARTY CLAIMS OR LOSSES OF ANY NATURE WHATSOEVER, INCLUDING, BUT NOT LIMITED TO, LOST PROFITS, PUNITIVE OR CONSEQUENTIAL DAMAGES."]
          [:h3 "6. LIMITATION OF LIABILITY"]
          [:p "IN NO EVENT SHALL district0x BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR LOSS OF PROFITS OR ANY DAMAGES WHATSOEVER FOR ANY REASON, INCLUDING RESULTING FROM LOSS OR USE OF DATA, MISUSE OF THE DISTRICT REGISTRY, OR ANY DECISION MADE ON OR THROUGH THE REGISTRY, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DISTRICT REGISTRY, DOCUMENTS, PROVISION OF OR FAILURE TO PROVIDE SERVICES, OR INFORMATION AVAILABLE FROM OR ON THE DISTRICT REGISTRY.  OUR LIABILITY IS LIMITED WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES, AND EVEN IF A REMEDY SET FORTH IN THIS AGREEMENT IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE."]
          [:h3 "7. RELEASE AND INDEMNIFICATION"]
          [:p "If you have a dispute with one or more Users, you agree to release district0x from any and all claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such disputes."]
          [:p "You agree to indemnify us, defend us, and hold us harmless from and against any and all claims, liabilities, and expenses, including attorneys’ fees, arising out of your use of the District Registry, including but not limited to your violation of this Agreement, provided that district0x (1) promptly gives you written notice of the claim, demand, suit or proceeding; (2) gives you sole control of the defense and settlement of the claim, demand, suit or proceeding (provided that you may not settle any claim, demand, suit or proceeding unless the settlement unconditionally releases district0x of all liability); and (3) provides to you all reasonable assistance, at your expense."]
          [:h3 "7. LINKS TO THIRD PARTY SITES"]
          [:p "LINKS FOUND IN THE DISTRICT REGISTRY MAY LET ENTER OTHER WEBSITES. YOU ACKNOWLEDGE THAT SUCH LINKED SITES ARE NOT UNDER THE CONTROL OF district0x, AND district0x IS NOT RESPONSIBLE FOR THE CONTENTS OF ANY LINKED SITE OR ANY LINK CONTAINED IN A LINKED SITE, OR ANY CHANGES OR UPDATES TO SUCH SITES. district0x IS NOT RESPONSIBLE FOR WEBCASTING OR ANY OTHER FORM OF TRANSMISSION RECEIVED FROM ANY LINKED SITE. district0x IS PROVIDING THESE LINKS TO YOU, IF ANY, ONLY AS A CONVENIENCE, AND THE INCLUSION OF ANY LINK DOES NOT IMPLY ENDORSEMENT OF THE SITE BY district0x."]
          [:h3 "8. MONITORING"]
          [:p "district0x shall have the right, but not the obligation, to monitor the use of the District Registry, to determine compliance with these Terms of Use and any operating rules established by district0x and to satisfy any law, regulation or authorized government request. district0x shall have the right, in its sole discretion, to edit, refuse to post or remove any material submitted to or posted through the District Registry. Without limiting the foregoing, district0x shall have the right to remove any material that district0x, in its sole discretion, finds to be in violation of the provisions hereof or otherwise objectionable."]
          [:h3 "9. INDEMNIFICATION"]
          [:p "You agree to defend, indemnify and hold harmless district0x, its affiliates and their respective owners, directors, officers, employees and agents from and against all claims and expenses, including attorneys’ fees, arising out of the use of the District Registry by You or Your Account."]
          [:h3 "10. TERMINATION"]
          [:p "district0x shall have the right to immediately terminate Your Account and/or remove You from the District Registry in the event of any conduct by You that district0x, in its sole discretion, considers to be unacceptable, or in the event of any breach by You of these Terms of Use."]
          [:h3 "11. PRIVACY POLICY"]
          [:p "To access the District Registry, you must explicitly consent to our privacy and data security practices. Our privacy and data security practices can be found by visiting our " [nav/a {:route [:route/privacy-policy]} "privacy policy"]]
          [:h3 "12. MISCELLANEOUS"]
          [:p "These Terms of Use constitute the entire agreement between each You and district0x concerning the subject matter hereof and supersedes all prior or contemporaneous understandings, agreements, representations, warranties, both written and oral, with respect to the subject matter hereof. Except to the extent applicable law provides otherwise, these Terms of Use and any access to or use of the District Registry will be governed by the laws of the State of California, without regard to the conflict of laws rules thereof. All disputes of any nature related to these Terms of Use shall be determined by final and binding arbitration in San Francisco County, California before a single arbitrator. The parties shall agree on the rules and procedures to be followed in the arbitration. If the parties are unable to agree on the rules and procedures to be followed within 15 days, the arbitration shall be administered by JAMS pursuant to its Streamlined Arbitration Rules and Procedures, and the arbitrator shall apply the laws applicable in the State of Delaware (without regard to the conflict of laws rules thereof). Judgment on the arbitral award may be entered in any court having jurisdiction thereof. The foregoing arbitration provisions shall not preclude either party from seeking an injunction or other provisional remedies in aid of arbitration from a court of appropriate jurisdiction. The arbitrator shall, in the arbitral award, allocate all or part of the costs of the arbitration, including the fees of the arbitrator and reasonable attorneys’ fees of the prevailing party, for payment by the non-prevailing party, and shall determine the prevailing party for this purpose. The parties further agree that (i) any claims brought by either party must be brought in such party’s individual capacity and not as a plaintiff or class member in any purported class or representative proceeding, and (ii) the arbitrator may not (x) consolidate more than one person’s claims, (y) otherwise preside over any form of a representative or class proceeding or (z) award class-wide relief."]
          [:h3 "13. SURVIVAL"]
          [:p "All provisions of this Agreement which, by their nature, should survive termination will survive termination, such provisions including, without limitation: ownership provisions, warranty disclaimers, indemnity, and limitations of liability."]]]]]]]))
